JARS.moduleAuto('tests.internals.Factories', [
    'CompletionHandler',
    'Config',
    'Dependencies',
    'Description',
    'Info',
    'Logger',
    'Options',
    'Parent',
    'ParentBundle',
    'ParentBundleName',
    'ParentName',
    'Ref',
    'Requestor',
    'State',
    'StateUpdater',
    'Strategy',
    'Subject'
]);
